name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.age_calculator_app }}
        TARGET_REPO: azizs4h/age-calculator-app
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: dist/
